### ISSUE TITLE
Use selected preset settings when duplicating a beacon

### ISSUE THREAD

**Issue by tommy290** [thommcgrath/Beacon#12]
I am a big fan of the preset settings for adjusting the quality/quantity for the different beacon types. However, if you duplicate an entire beacon (for example to make the bonus beacon) it doesn't apply those settings. It makes an exact copy of the beacon. I think it would be helpful to have those settings applied for all presets if you're copying them into a higher-tier beacon (standard to bonus, standard to cave, etc.).

**Comment by thommcgrath** [comment]
The problem is the preset may have been edited, so it's hard to determine user intentions here. If you copied a set, how can Beacon determine if you wanted to copy the preset or the set you've designed?

I've got a potential solution though. Adding loot sources is receiving a major overhaul. It'll be easier to add a handful of presets to a loot source, so simply selecting the same group of presets may be good enough.

**Comment by tommy290** [comment]
Another option might be a checkbox to indicate whether to apply preset settings. Maybe this would fit into the overhaul. Perhaps a popup occurs when you choose to duplicate a beacon. On the popup you could have a checkbox for applying preset settings, and maybe a list of all the presets so you can delete some if you don't want them all to be duplicated.

**Comment by thommcgrath** [comment]
That's a possibility. I'll consider it.
