### ISSUE TITLE
Vanilla Items overriding Modded Items

### ISSUE THREAD

**Issue by iMasonite** [thommcgrath/Beacon#155]
It seems that even with S+ items configured in the loot sets, their new Vanilla counterparts are being put in the actual drops. I'm only wanting Modded items in the drops.

Config: (all s+)
https://i.imgur.com/TCwcINA.png

Drop output: (red vanilla)
https://i.imgur.com/19ubqyF.jpg

**Comment by thommcgrath** [comment]
Unfortunately, this is an Ark issue. WildCard decided to use the same class strings as the original S+ items. It's always been ambiguous what gets chosen when there is more than one match, but mod authors avoided this by choosing unique names. WildCard pre-empted OrionSun's names for these items so this is the result. The only solution will be for OrionSun to rename these items, but since he's done with the project, it's not a good situation.

I'm closing the issue because this is not a Beacon bug, but feel free to reply.

**Comment by iMasonite** [comment]
Welp.. Thanks.
