### ISSUE TITLE
Item Set Weights Issue when included with defaults

### ISSUE THREAD

**Issue by shefski55555** [thommcgrath/Beacon#171]
The default value for an item set content's weight seems to be too high for adding it to the default loot pool of a drop which causes an issue when using "Add item sets to default"

The default item set weight of 500 seems extremely high given all example I have found given the default value as 1. Until I changed the item set's weight to 1 all drops were only spawning the item set I had added. I understand that the weights are just all added together to give a weighted % chance that the items will be selected but for the item sets the default value seems to result in added item sets being almost 500% more likely to be chosen over the defaults.

If I am correct and the default Item Set Weight is 1 could this potentially be addressed with a tool tip and possibly allowing decimal value inputs for the weights as currently it means that it is not possible to make an item set appear less frequently than the default ones.

**Comment by thommcgrath** [comment]
There's not a good solution to the problem, and part of the reason the feature was left out of Beacon for so long. Beacon only allows whole integer weights because a bug was discovered in Ark that, for some reason, throws off probabilities when using decimal weights. Beacon used to do it that way, and item set distribution was heavily weighted to a few sets, even with equal weight values. Switching to whole numbers solved the problem. But as you've seen, that leaves things in an awkward state when it comes to adding to the default loot.

I'll look into allowing decimal values as an "at your own risk" feature, but I don't expect I'll change the default values.

**Comment by shefski55555** [comment]
Ah I see typical Ark being awkward then, if possible then something that would inform the user of the default weight being 1 would also be helpful as currently just creating an item set and setting it to add the defaults leaves you expecting it to "just work". But due to the weight being so high compared to the defaults effectively only the added value spawns. 

The issue I had was that because only the added items were spawning I assumed it was an issue with bAppendItemSets=true not working properly.

**Comment by thommcgrath** [comment]
I'll see what I can come up with.
