### ISSUE TITLE
Numeric values for Min/Max Quality in Loot Presets

### ISSUE THREAD

**Issue by Nevcairiel** [thommcgrath/Beacon#174]
I've been trying to faithfully recreate the vanilla drop configuration in Beacon to get a starting point to start tweaking from, however I hit a snag.

I exported the loot item sets from the devkit and transformed it into a form that Beacon can import, however Beacon does not offer full numeric control over the Min/Max Quality settings inside item sets, only the pre-defined quality categories, so I cannot match the quality the original drops have (which for he "lvl 45 drops" loot item set is 1.25, for example).

Is that something I missed somewhere, or can this be added? I really like having control over this as closely as I can, so I can get an accurate starting point.

**Comment by thommcgrath** [comment]
You cannot set qualities in Beacon numerically because that’s just not how Beacon works. Quality numbers aren’t computer until the ini code is generated. But you’re in for a surprise.

In the dev kit, go to the ItemLootSet item (I think I have the name right) and right-click to choose copy. Then go to Beacon and paste it into a drop. That should save you some time, and it’ll parse the qualities accordingly. I think the dev kit assumes a difficulty of 1.0 / max dino level of 30, so you’ll want to set the difficulty in Beacon to get correct results. Or, as close to correct as possible.

Decimal weights are coming this week. Though they are very much a “use at your own risk” feature. There is a bug in Ark that causes improper distribution of randomness when using fractional weights. This is why the drops always seem to contain a water jar or crop plot for example. So Beacon switched to whole numbers to solve the problem. But when using the “add item sets to default loot” option in Beacon, it’s impossible to match weights with the defaults without the decimals. So it’s kind of a lose-lose situation.

**Comment by Nevcairiel** [comment]
The copy/paste is pretty nice, but unfortunately its not 100% flawless, since it doesn't properly deal with defaults, since the Ark Editor will not include values that are set to defaults in the copy/paste.

For example, "bForceBlueprint" defaults to true, so if its set, then it'll not be in the copy/paste, same for EntryWeight, which defaults to 1.0.  So if there is an item entry with bForceBlueprint set, then Beacon won't see that, and not force it to 100% BP chance (the entry has a 0.5 Chance to Blueprint Override, for some reason). If I manually add "bForceBlueprint=true", then it works.

If you could make it properly deal with defaults (primaly those two mentioned above), then I could scrap my entire pre-processing script that I've been toying with, which reads the line and adds the missing default fields to make Beacon happy. :)

**Comment by thommcgrath** [comment]
Thanks for the paste, I’ll investigate it.

**Comment by thommcgrath** [comment]
So in my tests, bForceBlueprint works. Beacon's code (if you're interested) is

```xojo
' If bForceBlueprint is not included or explicitly true, then force is true. This
' mirrors how Ark works. If bForceBlueprint is false, then look to one of the
' chance keys. If neither key is specified, chance default to 0.
Dim HasExplicitChance As Boolean = Dict.HasKey("ChanceToActuallyGiveItem") Or Dict.HasKey("ChanceToBeBlueprintOverride")
Dim ForceBlueprint As Boolean = if(Dict.HasKey("bForceBlueprint"), Dict.Value("bForceBlueprint"), Not HasExplicitChance) // Default is true in-game
Dim Chance As Double
If ForceBlueprint Then
  Chance = 1
Else
  If Dict.HasKey("ChanceToActuallyGiveItem") Then
    Chance = 1.0 - Dict.Value("ChanceToActuallyGiveItem")
  ElseIf Dict.HasKey("ChanceToBeBlueprintOverride") Then
    Chance = Dict.Value("ChanceToBeBlueprintOverride")
  Else
    Chance = 0
  End If
End If
Entry.ChanceToBeBlueprint = Chance
```

Which basically says if bForceBlueprint is true, set the chance to 100%. Otherwise, use ChanceToActuallyGiveItem if available, ChanceToBeBlueprintOverride otherwise, and 0% if neither are set. The paste you gave me has bForceBlueprint set to false and ChanceToBeBlueprintOverride to 0.5, so that's why Beacon reads it as 50%.

**Comment by Nevcairiel** [comment]
Sorry if it wasn't clear,  but the problem is not the last entry which has bForceBlueprint=false, but the other 2 entries which don't have bForceBlueprint at all.

In the ARK DevKit, if bForceBlueprint is true, then the ARK DevKit will not include it at all in the string. So in this case, Beacon would have to interpret the absence of it as True. In your code, this means changing the "Dim ForceBlueprint" line to always set it to True if its not explicit, instead of setting it based on the HasExplicitChance variable. Your comment even says as much, but the code disagrees.

Similarly, for EntryWeight, if its not set explicitly at all, then the game assumes its 1.0, so thats what Beacon should do to make this copy/paste function perfect.

**Comment by thommcgrath** [comment]
Ah, I get what you're saying now. Ok, I can make that happen.

**Comment by Nevcairiel** [comment]
Cool thanks, I'll try in the next release.
