### ISSUE TITLE
not importing nitrado blank page

### ISSUE THREAD

**Issue by VillinWarrior1984** [thommcgrath/Beacon#175]
when I click import then click on nitrado blank page pulls up dose not pull up the log into nitrado screen

**Comment by thommcgrath** [comment]
You’ll need to check your system for something blocking requests to either Nitrado or beaconapp.cc. At best I might be able to detect the problem and add a warning dialog, but there’s nothing I can do when the computer can’t reach one of those two sites.

Some anti-malware is aggressive and will block unsigned apps from accessing the Internet, so check that first. You may need to put Beacon into your whitelist.

**Comment by VillinWarrior1984** [comment]
I have no anti virus protector as of the moment how do I go about checking what's blocking it
    On ‎Wednesday‎, ‎April‎ ‎17‎, ‎2019‎ ‎09‎:‎10‎:‎55‎ ‎AM‎ ‎CDT, Thom McGrath <notifications@github.com> wrote:  
 
 
You’ll need to check your system for something blocking requests to either Nitrado or beaconapp.cc. At best I might be able to detect the problem and add a warning dialog, but there’s nothing I can do when the computer can’t reach one of those two sites.

Some anti-malware is aggressive and will block unsigned apps from accessing the Internet, so check that first. You may need to put Beacon into your whitelist.

**Comment by thommcgrath** [comment]
I’m sorry but I don’t know. There are tons of possibilities from Windows Firewall (which is unlikely) to some program I’m not aware of, router settings, or even a downed route between you and one of the target sites. These issues are very hard to diagnose.

There are simple things to check first though. Try visiting https://api.beaconapp.cc/oauth/?provider=Nitrado _using the browser on the same computer you’re running Beacon on_. If it loads the Nitrado login page, we know it isn’t your router or a bad route. If it doesn’t load, your browser might give you some clue as to why. Don’t bother logging in though, it won’t do you any good.

If it loads, then the problem is definitely something on your computer blocking Beacon, but I don’t know what that could be if you really don’t have malware protection installed.

**Comment by VillinWarrior1984** [comment]
it loaded but it is a bran new laptop so im not sure how to go about checking whats blocking it I don't really have anything on the computer yet
    On ‎Wednesday‎, ‎April‎ ‎17‎, ‎2019‎ ‎09‎:‎24‎:‎14‎ ‎AM‎ ‎CDT, Thom McGrath <notifications@github.com> wrote:  
 
 
I’m sorry but I don’t know. There are tons of possibilities from Windows Firewall (which is unlikely) to some program I’m not aware of, router settings, or even a downed route between you and one of the target sites. These issues are very hard to diagnose.

There are simple things to check first though. Try visiting https://api.beaconapp.cc/oauth/?provider=Nitrado using the browser on the same computer you’re running Beacon on. If it loads the Nitrado login page, we know it isn’t your router or a bad route. If it doesn’t load, your browser might give you some clue as to why. Don’t bother logging in though, it won’t do you any good.

If it loads, then the problem is definitely something on your computer blocking Beacon, but I don’t know what that could be if you really don’t have malware protection installed.

**Comment by thommcgrath** [comment]
Unfortunately I don't have much more advice for you.
