### ISSUE TITLE
Selecting Island and Scorched for items

### ISSUE THREAD

**Issue by rob-bb** [thommcgrath/Beacon#20]
Hi,  

When I select to add scorched earth items to an items set and tick the box for them that seems ok, but when I go back to edit the set the SE items have been unticked again.

**Comment by thommcgrath** [comment]
Ok, here's what is going on. When right-clicking an item set and choosing "update preset" you're using that item set as a template. Everything, including name, min and max, etc gets copied it. You're not so much updating the preset as you are replacing it. This is why the checkboxes get reset.

To edit the preset, use the Preset Library which will correctly preserve those settings, as its a true edit function.

And I know this feels like an excuse. I've just spent some time trying to make it work this way, as I admit that feels more intuitive. But the problem is the update is somewhat subjective. Let's say you have a set with two different entries of the same item, perhaps a low quality with more quantity and a low quantity with extra quality. Just an example. Now let's say you delete one and edit the other. When you go to update, which of the original two should that remaining one be matched with? I can't look for a perfect match, things will be changed. So the only logical thing that can be done is a rebuild.

**Comment by rob-bb** [comment]
Thanks for explaining that, it makes sense to me now.
