### ISSUE TITLE
1.5.0a1 Bug - Damage Numbers Setting

### ISSUE THREAD

**Issue by YarbySauce** [thommcgrath/Beacon#218]
![DamageNumbersSetting](https://user-images.githubusercontent.com/44554851/101301398-b5716980-3806-11eb-8903-7c6e80aefc61.PNG)

The damage numbers setting is being added to the bottom of the GUS.ini instead of replacing the base one.

**Comment by thommcgrath** [comment]
Yeah, this was reported on Discord too. It's not exclusive to any particular setting, it has something to do with how the configs are merged together. The easiest workaround for now is to add [ServerSettings] to the top of GameUserSettings.ini custom config used in each config set.

**Comment by YarbySauce** [comment]
Roger, I'll do that for now.

**Comment by YarbySauce** [comment]
A heads up, the workaround does not work using the Deploy option.

**Comment by thommcgrath** [comment]
Hmm. Another user reported success, including with deploy. I wonder what's different.

**Comment by YarbySauce** [comment]
![DamageNumbersSetting_deploy](https://user-images.githubusercontent.com/44554851/101301226-25cbbb00-3806-11eb-95e0-82c93e4eb376.PNG)

**Comment by thommcgrath** [comment]
Ok, after investigating, there's a couple issues going on here. In the most recent screenshot, ShowFloatingDamageText is still there, I believe, because the previous deploy put it there but not removed since Beacon doesn't touch what it doesn't know. In this case, it's erring on the side of caution and leaving it there. Remove it yourself and it probably won't come back if the [ServerSettings] is explicitly part of each custom config content.

The double values are a tougher problem to solve. Beacon keeps track of ini config options so that it'll know that a config should have exactly one TamingSpeedMultiplier (for example) but can allow multiples of others like PreventDinoTameClassNames. This helps it decide what to do when merging. The trouble here is that ShowFloatingDamageText is *not* an ini option. It's a launch option, which means the value set at launch will overwrite whatever is in GameUserSettings.ini anyway. So changing it there isn't actually viable. But also since it's a launch option, Beacon doesn't know what to do with it in GameUserSettings.ini so it again errs on the side of caution and includes both.

There's a few potential solutions, but all come with compromise. Beacon could potentially allow some sort of syntax to mark unknown values as limited or unlimited in quantity. But this would be a clumsy solution, and won't achieve your goal anyway. It probably makes more sense for Beacon to look for launch options in GameUserSettings.ini and automatically set them on Nitrado servers during deploy. This would be awkward though because Beacon will know they don't belong there but will need to treat them as if they do. Still, it seems like the most reasonable thing to do.

**Comment by YarbySauce** [comment]
I just removed it from the base config & added an "ON" & "OFF" config & will choose it depending on the map...

**Comment by YarbySauce** [comment]
Another setting that gets messed up & isn't doing multiples of it is the TamedDinoClassResistanceMultipliers setting in the game.ini.

**Comment by thommcgrath** [comment]
Yes, all settings are prone to this. Beacon doesn't actually know much of anything about them, so it doesn't know there should be only one. That will change in alpha 2.

**Comment by thommcgrath** [comment]
The fix is now available in 1.5 alpha 2.
