### ISSUE TITLE
Adding Item Does Not Work (Preview Nor Current)

### ISSUE THREAD

**Issue by Kozenomenon** [thommcgrath/Beacon#220]
Installed current version to add my mod and item. Was able to confirm ownership of mod. Added item and on publish it errors on Mod ID must be numeric. Since it seems it might be relevant for the error msg- The mod was recently added to workshop so it's Mod ID is > Int32 max value. (but that's nothing new- steam workshop surpassed int32 max about a year ago)

Then I installed the preview version. Added the item again- it was lost somehow from the upgrade? Not sure if that is to be expected. Mod was still there. After adding the item details, on publish get different error for 'min_version' cannot be null. 
https://i.gyazo.com/d1d7d9adacd3af028b22eb4af147be1b.png

**Comment by thommcgrath** [comment]
Thanks for bringing this to my attention. Hopefully I can fix it at the API level, but I'm not sure yet.

**Comment by thommcgrath** [comment]
Ok, so the good news is this is fixed, but the bad news is it can only be fixed in the app. It just isn't sending the mod uuid with the blueprint, so I can't pull that out of thin air.

If you're curious, here's a bit of background to explain the effects you're seeing. The stable version of Beacon, 1.4, uses Beacon v1 API, which I don't maintain much, thus the errors you see. I'll probably go in and make the errors nicer, but the core issue is that new engrams must have that `min_version` value, and the v1 API cannot provide it. It's due to a complicated mess with certain structure-related mega-mods sharing each other's paths, which Beacon assumed to be unique. Beacon 1.5 and the v2 API break this assumption, but it means new mods are only supportable in Beacon 1.5 and newer.

But in Beacon 1.5 the blueprint manager isn't including the mod uuid for the new blueprints, so the API basically just skips over them. That's why they vanish when you publish in 1.5. I can (and should) have that throw an error instead.

The fix for this will be included in Beacon 1.5.0.2 which is due for release to the stable branch on Tuesday February 16th.
