### ISSUE TITLE
ConfigSubtractNPCSpawnEntriesContainer issue

### ISSUE THREAD

**Issue by brown-star** [thommcgrath/Beacon#238]
Beacon adds an entry weight when using subtract from the spawn entries. This causes the line to be ignored.

ConfigSubtractNPCSpawnEntriesContainer=(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesDamiensAtoll_C",NPCSpawnEntries=((AnEntryName="HerbIslandSpawn",EntryWeight=0.5,NPCsToSpawnStrings=("Sauropod_Character_BP_C","Stego_Character_BP_C","BionicStego_Character_BP_C"))))

should read:
ConfigSubtractNPCSpawnEntriesContainer=(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesDamiensAtoll_C",NPCSpawnEntries=((AnEntryName="HerbIslandSpawn",NPCsToSpawnStrings=("Sauropod_Character_BP_C","Stego_Character_BP_C","BionicStego_Character_BP_C"))))

**Comment by brown-star** [comment]
this is also on the replace function, causing it to be ignored.

**Comment by thommcgrath** [comment]
This definitely got my curiosity going, so I spent some time running a whole bunch of tests to confirm. What I found was that you're on the right track, but came to the wrong conclusion.

Here's what I did. I started each test with the following string of commands to get me to a clean slate, then circled herbivore island on The Island until I would see one of the removed creatures:

```
cheat destroywilddinos;cheat infinitestats;cheat god;cheat fly;cheat slomo 10;cheat settimeofday 08:00
```

In the first test, I tried the code generated by Beacon, exactly as you provided here. Then I tried EntryWeight of 1.0 and 0.0, and then your second line, that has no EntryWeight value at all. In all four of these tests, I found stegos, occasionally tek stegos, but never any brontos. So I theorized that Ark doesn't care about EntryWeight at all (and that Beacon could remove it safely) and instead is removing only the first creature in each set. So I used Beacon to generate the following line:

```
ConfigSubtractNPCSpawnEntriesContainer=(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesDamiensAtoll_C",NPCSpawnEntries=((AnEntryName="Stego",EntryWeight=0.5,NPCsToSpawnStrings=("Stego_Character_BP_C")),(AnEntryName="Tek Stego",EntryWeight=0.5,NPCsToSpawnStrings=("BionicStego_Character_BP_C")),(AnEntryName="Bronto",EntryWeight=1,NPCsToSpawnStrings=("Sauropod_Character_BP_C"))))
```

Sure enough after lots and lots of circling, for much longer than I needed in the other tests, not a single one of the three dinos appeared. So that's what's going on. You need one spawn set per removed creature.

As for the replace, I'm not sure what you mean. Are you talking about `ConfigOverrideNPCSpawnEntriesContainer`?

**Comment by brown-star** [comment]
Ahh that is good news...So we can ignore the weight, because it is ignored...and I have also tried the multi entries per container and it does seem to be working as intended..thank you again.

**Comment by brown-star** [comment]
Oh...on the replacements...it is the creature replacement...Here is a pic:

https://i.imgur.com/ER7Y3eU.png

This outputs the following:
ConfigSubtractNPCSpawnEntriesContainer=(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesDamiensAtoll_C",NPCSpawnEntries=((AnEntryName="Remove",EntryWeight=0.5,NPCsToSpawnStrings=("Trike_Character_BP_C"),NPCRandomSpawnClassWeights=((FromClass="Thylacoleo_Character_BP_C",ToClasses=("Raptor_Character_BP_C","Thylacoleo_Character_BP_C"),Weights=(50,50))))))

**Comment by thommcgrath** [comment]
Oh. Well that doesn't make any sense. Why would you add a replacement to a remove point?

**Comment by brown-star** [comment]
ahh...I was trying to not have x creature but instead spawn y and z...I guess it needs to be in the add LOL thanks again
