### ISSUE TITLE
Exported item sets are doubled for blueprint % between 0 and 100

### ISSUE THREAD

**Issue by akmaslov** [thommcgrath/Beacon#24]
If I have an item (equally weighted with others in the same set) that has a 20% chance of spawning as a blueprint, a Bola for instance, I would expect the following output string: 
```
(EntryWeight=1.000000,ItemClassStrings=("PrimalItem_WeaponBola_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=3,MinQuality=0.000000,MaxQuality=0.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.2)
```

But what I get instead are actually two strings:
```
(EntryWeight=0.800000,ItemClassStrings=("PrimalItem_WeaponBola_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=3,MinQuality=0.000000,MaxQuality=0.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0)
(EntryWeight=0.200000,ItemClassStrings=("PrimalItem_WeaponBola_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=0.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0)
```

Is there a reason for this? Mathematically that works out to do approximately what I want, but it does mean that I can now get a duplicate of both the item and the associated blueprint. Normally that's not a big deal, but for full armor set drops with potential blueprint replacements, I easily end up with two hats and two pants instead.

**Comment by thommcgrath** [comment]
Yeah, it is intended because it is likely closer to your intentions than what Ark would do otherwise.

Let's say you have a stack of 40 rifle bullets with a 20% blueprint chance. This could be interpreted a few different ways:

1) 20% chance of a rifle bullet blueprint or 80% chance of 40 rifle bullets.
2) 20% chance of 40 rifle bullet blueprints or 80% chance of 40 rifle bullets.
3) Approximately 8 rifle bullet blueprints and 32 rifle bullets.

Which of the options makes the most sense, and which option do you expect Ark to take?

Ark takes option #3. The blueprint chance applies to each individual item in a quantity. So each bullet gets that 20% chance.

Beacon outputs this way to emulate option #1 as close as possible, though as you point out, is not perfect. A case could be made for #2, but nobody would ever want so many of the same blueprint.

**Comment by akmaslov** [comment]
Aye, I just got to the bottom of the closed issues list and saw a similar ticket. Makes sense to me. Ark is so bloody weird sometimes. 

While I have you on the line, I'm looking at this [reddit thread](https://www.reddit.com/r/playark/comments/56dnpi/beacon_the_loot_source_configurator_has_been/d8m1w8x/) about loot quality and how random it is. I'm seeing a similar issue where low- and high-end qualities seem to hug their boundaries an awful lot. A basic beacon with Primitive-Ramshackle settings seems to drop exclusively low-end Primitive, while a Cave node with Journeyman-Ascendant settings seems to drop Ascendant almost every time.  

If I'm trying to wrangle in quality randomness, would you recommend I move away from min-max settings and just set both to the same approximate thing I want?

**Comment by thommcgrath** [comment]
What I do on my server is set the range to what I want in Beacon. It seems to work out pretty balanced to me, but that's purely anecdotal.

Trial and error is the best I can recommend. Craft some loot sources, then use cheat commands to spawn them and see what they contain. Adjust from there. I think Beacon makes this much easier, but it still has to fight Ark's uphill battle of weirdness.

**Comment by akmaslov** [comment]
I am seeing an odd issue with minQuality being higher than maxQuality, for instance:

```
(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_ChitinPants_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=3.750000,MaxQuality=2.750000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),
(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_ChitinPants_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=3.750000,MaxQuality=2.750000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0)
```

Could that be the culprit? I'm using the latest version (Beta 8).

**Comment by thommcgrath** [comment]
Sure seems like it. I'll check it out myself, but I haven't seen this, so just double-check that you have the min and max quality set as you expect in your file. Beacon allows you to set it this way - which admittedly it should - so it's possible this is user error.

Not trying to blame you, like I said I'll confirm it myself, I'm just suggesting you check while I do so.

**Comment by akmaslov** [comment]
Looks right to me. Here's my beacons file. 

[beacons3.zip](https://github.com/thommcgrath/Beacon/files/718380/beacons3.zip)

**Comment by thommcgrath** [comment]
Ah, ok. Yes, actually, this is correct. Here's what is happening.

Every loot source in Ark has automatic built-in quality multipliers. So a 1.0 quality in a blue cave drop is different from a 1.0 quality in a white beacon. The loot sources have both a minimum multiplier and maximum multiplier.

This is why Beacon uses named qualities instead of values. When you say you want Journeyman to Mastercraft, Beacon uses that along with the loot source's hidden multipliers to compute a number that is most likely to give you what you intended.

In this exact case, a blue cave drop has a min multiplier of 1.75 and max multiplier of 2.5. Journeyman has a quality of 3.75 and mastercraft has a quality of 5.5. So the math goes like this:

3.75 / 1.75 = 2.142857143
5.5 / 2.5 = 2.2

Which brings me to a new issue. You _have_ found a bug, just not the one you think. You should notice that my math doesn't line up with the numbers you see exported. This is because I screwed up and Beacon is currently truncating the loot source multipliers, so it is currently doing

3.75 / 1 = 3.75
5.5 / 2 = 2.75

Which is not correct.

**Comment by akmaslov** [comment]
Sweet! Are you pushing out a new build?

**Comment by thommcgrath** [comment]
Yes, just not sure when. Probably over the weekend.

**Comment by akmaslov** [comment]
Sounds good, looking forward to it!
