### ISSUE TITLE
0% chance for blueprint when using default loot drops

### ISSUE THREAD

**Issue by Forien** [thommcgrath/Beacon#251]
When adding loot drop with "load default content when available" checked, % chances for blueprint are always 0. They shouldn't be. I don't know details myself, but I would love to have vanilla drops as a starting point for my changes and original values would be highly appreciated. 

![image](https://user-images.githubusercontent.com/11304207/174921779-a3c8bf49-603c-449c-9936-e2878917ff57.png)

On the same note, these sets do not appear in Templates screen, and quality seems weird, since I remember getting mastercrafts as well (in vanilla), not only apprentice, but I guess that's then somehow scaled with difficulty.

However, [according to Wiki](https://ark.fandom.com/wiki/Supply_Crate#Possible_Loot_.28The_Island.29), Island's "Red with ring" should have `Quality range: 200% - 250%` on it's own and then items should have it's own `125%` quality on top of that (with a chance to be bp). I trust this works fine, but could use some explaining in documentation/help menu (maybe with maths behind it if you know it).

**Comment by thommcgrath** [comment]
This is unfortunately a bug with Purlovia, the data mining project that supplies data to the official wiki, Beacon, Ark Smart Breeding, and other projects. When updated for the Fjordur update, the `forceBP` key was removed in favor of the `blueprintChance` key. In theory, this is a great change. In practice, neither key shows up in any of the drop data.

I've reported this issue to them, but I'm still waiting on a fix.

**Comment by Forien** [comment]
Ok, great, thanks for clarifying. Hopefully this gets fixed reasonably soon :)

So I guess the qualities are also from the same source and they are correct?

**Comment by thommcgrath** [comment]
Yes, it comes from the same source, and it is accurate. Beacon's qualities are going to be more reliable than the wiki, as the wiki is designed to be human-readable, so a lot of the information is simplified. That 200% to 250% you see it's the crate's quality multiplier. For example, the same information can be seen at https://usebeacon.app/object/c14f94e4-8d12-4921-879f-10427f098d46 next to the Multipliers label. All that means is if something was requested at quality 5, the crate would pick a random multiplier between 2 and 2.5, so the actual quality would be 10 to 12.5. Beacon knows all this, and automatically counters the crate's multipliers so you get the quality you intended. It does this while importing from the data mining results too, so it'll start from that 10 to 12.5 range (again, just an example) and pick its own quality tiers that are most likely to produce the same effect for that crate.

There's a lot going on because quality is a complex subject in Ark. Most games too, I'd imagine.

**Comment by thommcgrath** [comment]
This has been fixed as of the June 25th, 2022 at 5:44 AM UTC data update.
