### ISSUE TITLE
Custom config not showing in export of game ini.

### ISSUE THREAD

**Issue by Velithil** [thommcgrath/Beacon#257]
Just as the title says. Some custom config, not all, is not showing up on the exported game ini.

An example is I changed a loot drop on a Dino to include a mod item. Now the line has been tested and is working correctly but any time I go and export the game ini from Beacon it doesn’t have that line in it and I am having to grab the line from custom config.

**Comment by thommcgrath** [comment]
This is by design. Add your mod drop and items to the Blueprints section using the instructions at [https://usebeacon.app/help/adding_blueprints_to_beacon](https://usebeacon.app/help/adding_blueprints_to_beacon). You can then use it like any other drop in Beacon.

When using a group of settings such as the Loot Drops group, Beacon will ignore that group's settings in custom config. It does this to reduce complexity when merging settings from multiple config sets.
