### ISSUE TITLE
Problem with exporting

### ISSUE THREAD

**Issue by Ansem774** [thommcgrath/Beacon#59]
So ever since the last update to your beacons app, I've noticed it's been butchering the exports for the double drops. It's basically not carrying the min/max quality correctly. The standard drops work as far as I know and you'll see that in the screen shots, but the double drops are being forced with lower quality than selected. The only counter to fix this would to be manually changing them all to the correct numbers, but see the point of using your app is to save hundreds of editing hours for the custom drops. I wanna thank you for everything you do, this has been the MOST used app in my list ever since I got into running my own server. It's a must. I can easily speak for the community and say we all appreciate what you do and also that you still continue to update this program. So thanks, thanks so much. I hope you can get me some insight into fixing my issue so our drops can become normal again.

Standard White Drop Config: https://i.gyazo.com/d0171ab8c1113e7f78845dd1668e8484.png
Double White Drop Config: https://i.gyazo.com/efdf5feabf97310744633b9cb3b252da.png
Export: https://i.gyazo.com/8f998213630fab7530e7151d634be1f7.png

**Comment by thommcgrath** [comment]
No, the export is correct. Each loot source in Ark has built-in multipliers, which Beacon is aware of. What Beacon exports correctly accounts for the loot source multiplier and server difficulty. That's why the same quality choices in Beacon will produce different values in the export depending on the loot source.

**Comment by Ansem774** [comment]
This makes absolutely no sense. It was working perfectly before, now the loot quality has tanked for the export when it comes to the doubles, and I know for a fact its not working as intended because I'm getting primitive drops when my config clearly states the lowest possible being mastercraft. Yet it still drops primitive and never drops mastercraft or ascendant. The export reflects it dropping primitive - apprentice and that's what I get. 

My difficultly is default or in this case (150 wilds) and my loot quality multiplier is ark config is 5, (Max). Yet I get nothing that my beacon config says It should be giving and this was confirmed when the config export shows it being lower. I can almost bet if I manually put in the quality it will work, so the export is definitely not reflecting the correct config. I'm fully at a loss here. Something since the last update has made this no longer working.

**Comment by thommcgrath** [comment]
Make sure your document's map and difficulty matches your config, and remove the loot quality multiplier config. Beacon will compute correctly if its settings match the server settings.

**Comment by Ansem774** [comment]
The config settings for the difficulty in the beacons matches my game config, so I'm assuming your talking about removing the multiplier from my config in the game correct? Thanks for the help, ill try that now.

**Comment by thommcgrath** [comment]
My concern is that with a loot multiplier set, you should be receiving *higher* quality loot, not lower quality.

**Comment by Ansem774** [comment]
Yea, I am without a doubt receiving WAY LOWER loot from my doubles compared to my standard drops. The export also seems to reflect it correctly. My standard quality is giving me 1.28 - 4.8 but the double says 1.6 - 1.60 which makes no sense. All I know is with it setup like this with my multiplier at the max (5), Doubles give primitives and up to like apprentice. Haven't fully tested but it's giving me primitive and nowhere in the beacons config did I put primitive for items. Other than arrows and ammo ofc.

**Comment by thommcgrath** [comment]
Share your GameUserSettings.ini please and your Beacon document(s).

Like I said previously, don't rely on the quality values in the export, because they will be misleading. That doesn't mean they are wrong though. A standard white drop has a min multiplier of 1.0 and max multiplier of 1.0, so essentially the quality won't be changed from your selection. However, a double white as a min multiplier of 2.0 and a max multiplier of 2.5, so Beacon will adjust the quality values to compensate. This document has a couple charts that might make it easier to understand: https://beaconapp.cc/help/math.php

**Comment by Ansem774** [comment]
https://drive.google.com/file/d/0B1C08FCMG8YgMVRlYmVGcnByUTg/view?usp=sharing

**Comment by thommcgrath** [comment]
According to GameUserSettings.ini, you have the line `DifficultyOffset=0.200000`, but your Beacon document has difficulty offset set to `1.0`. Unless your difficulty is being changed by a command line parameter, this is definitely the problem. Beacon is altering its quality numbers differently than how your server is configured.

Maybe this was done with the loot quality multiplier. Because 0.2 * 5.0 would be 1.0. The effect would be a low dino max level of 36, but still normal quality loot. In theory this should work fine. In practice, maybe the new quality multiplier isn't working as expected?

My recommendation is to remove SupplyCrateLootQualityMultiplier from GameUserSettings.ini, set the Beacon difficulty offset to 0.2, and try again. It should achieve the desired effect.

**Comment by Ansem774** [comment]
yea the command line is controlling the difficulty I'm assuming. The stupid server host I use does it like this. "OverrideOfficialDifficulty=5" is pulled from my command line. Like you said, in theory this should be working fine. My wild dinos are in fact Lv.150, so something is up with this config thing. I'm going to assuming its from faulty configs, ill sit down and play with it tonight, thanks for all of your help. Your program seems to be working fine and there is just a confusion between configs for sure.
