### ISSUE TITLE
Non-admin install for Windows

### ISSUE THREAD

**Issue by Tahvohck** [thommcgrath/Beacon#73]
At the moment, Beacon requests elevation to install on Windows, regardless of whether or not the software is installed in a restricted location (`C:\Program Files` or `C:\Program Files (x86)`). If the installation needs elevation for that location only, I'd advise it not request elevation until the location is confirmed to need it OR that a zip file be provided for nonstandard locations, whichever would be simpler.

**Comment by thommcgrath** [comment]
Neither would be particularly great. The installer is doing more work than just copying files. It sets up file associations, a url handler, and enables TLS 1.2 on systems that require it which is an admin operation. You are welcome to review the installer script at https://github.com/thommcgrath/Beacon/blob/master/Installers/Windows/Setup.iss to see that it alters HKCR and on some systems HKLM.

**Comment by Tahvohck** [comment]
Ah, that's unfortunate. I do see in the installer where that would break. File associations and the URL handler could be option easily enough, but is there an actual need to modify the system-wide TLS settings other than personal security mantra? I agree that systems need to transfer/modernize, but see no reason why Beacon should be making that decision for the user. It seems almost too intrusive for what Beacon is.

**Comment by thommcgrath** [comment]
There is no reason that TLS 1.2 should not be enabled. On affected systems, Beacon cannot communicate with the server to check for updates, download updated engram data, or interact with the document library. Beacon has a number of online features, and the server speaks only TLS 1.2. Modern browsers have no problem with this, but the WinHTTP library has TLS 1.1 and 1.2 disabled by default on Windows 7 and Windows 8.0. So on those systems, assuming the value has not been modified from the default, the installer attempts to "correct" the issue. The installer will not alter the value on Windows 8.1+ or when the value is not the default.

As for the root issue, what are you trying to accomplish? A portable installation?

**Comment by Tahvohck** [comment]
Portable or per-user installation, yes. While it can be assumed that the average user has administrator privileges on their machine this isn't always true or even desirable, and Beacon falls into a subset of programs where it _seems_ like it should be portable-capable: it is, after all, a utility and a fairly self-contained one at that. It seems that this assumption is wrong, and changing it would require deep changes to the core operation of the program.

This is hardly a make-or-break issue, but more one of personal feelings on how a program should operate given how it presents itself to the user. Reconciling that is obviously going to come down to how the core devs feel on the issue.

**Comment by thommcgrath** [comment]
A portable install could happen, but I'd need to make the app support it first. There is user-specific data stored in %AppData% that would need to be relocated for a portable install, and of course Beacon would then need to be able to look for it there.

A per-user installation is more of a problem, as file associations must point to a single global exe. Obviously, a portable install would need to forego these so there would be a loss of functionality that is expected of a portable install. But for a per-user install, that loss of functionality isn't great.

**Comment by Tahvohck** [comment]
I'm inclined to agree. Were it up to me and I wanted to support legacy systems being able to download, I'd look into a way for the server to support TLS 1.0 only for engram data or document library since those can probably be considered not at risk for attacks, but preliminary looking shows TLS 1.0 as vulnerable against both POODLE and BEAST. I'm finding it difficult to ascertain whether or not that would put the server itself at risk. At this point, it's probably far past "more complicated than it's worth".

The simpler solution would probably be a check against the system capabilities during installation, ask the user if they care, and ask for elevation if they do. I don't know how installers work well enough to know if that's as simple as it sounds like it should be.

**Comment by thommcgrath** [comment]
If I were using an expensive paid installer tool such as Advanced Installer, I could do something like that. InnoSetup is an excellent free installer - arguably the best - but logic such as that is a bit out of its reach. I could probably write some python scripts to extend its intelligence, but it's getting well into "not worth it" territory.

Regarding server security, there are options but none of them good. If I were to run 2 http processes on the server on different ip addresses, I could serve different capabilities on each, and therefore offer API data on a reduced security connection. Do I have any desire in doing that? None at all.

I'm a believer that all websites should be HTTPS-exclusive. Even Beacon's, as the website links to downloads which I'd hate to be tampered with by some jerk in a coffee shop altering the destination for all exe urls, for example. Since the website allows you to download executable code, security should be kept high. And I don't think you're suggesting I reduce the security requirements, I'm just explaining the reasoning behind my decision.

**Comment by Tahvohck** [comment]
Technically you could do similar with virtual hosts running on a single apache instance (or whatever you use) but yeah, it's all more than it's worth for edge cases. Thanks for taking the time to break down your reasoning for me, I think this has been discussed well enough to leave as-is. I'm not closing this in case you want to add further information, but I am going to change to title.

**Comment by Siernan** [comment]
Is this still a "wontfix"? It's 3+ years later :); Windows 7 is unsupported by Microsoft, TLS 1.0 and 1.1 support are deprecated by most major players, and the general state of the world has changed (for the better?). I'm with the original author's mentality that this is a piece of software that absolutely _could_ and depending on the context, maybe even _should_ be a per-user install.

I agree that your application and site should not compromise in the slightest on security aspects but I am not sure that your installation mechanism should be altering their OS security posture by changing TLS related registry keys and installing Windows Update files, particularly since this is not advertised (unless you go digging in the install script, since this is open source). I don't see TLS 1.2+ enablement listed in the system requirements on the download page or anywhere else other than within the context of this discussion. I believe it would be more beneficial to list that in the requirements (since it is one). Then, if you're feeling kind, provide the guidance on installing/validating that requirement on the same page or within the installer if possible (though from your discussion that logic is potentially unavailable to you). Do you have any telemetry on whether it would significantly affect your userbase to no longer support Windows 7 or Windows 8.0 and thus just neatly sidestep this issue?

Remaining are the URL handler and file associations that you create. Are these possible to do in a per-user context (at all or with Inno Setup)? What URL handler and file associations do you create? Would the current behavior of the app be severely hampered if a user chose to do a per-user install (assuming you took the time to alter your application to provide the option) and these two things were impossible to do?

Apologies if this was inappropriate to post here and sorry for the wall of text.

**Comment by thommcgrath** [comment]
While I agree that there is value in improving the requirements page, I’m not quite ready to give up on Windows 7 and 8 yet. Beacon’s installer only tweaks the registry keys if they have not been previously altered. So if somebody explicitly wants TLS 1.2 turned off, the installer will do nothing in that regards. There isn’t really a better way to handle this, as most users have no idea what this even means.

The file and url associations are still the biggest problem and cannot be done per-user. It’s just how Windows is. The URL associations are less critical, they just support things like being able to open projects from the user’s browser. But the file associations being missing would be quite a problem for users, as the `.beacon` files would not be associated with Beacon. So somebody double-clicking a project would get the “you have no program to open this” window, and their project icons would be blank.

**Comment by Siernan** [comment]
I'm ready to throw 7 and 8 to the wolves myself haha, but I can agree to disagree :).

Could the per-user installer exist as an advanced install option with the caveat that the user would have to manually set the file association themselves post-install (Properties window or in the Settings>Apps>Default Apps>Choose default apps by file type)? Or is that in the previously mentioned "more complicated than it's worth" category haha?

I appreciate the replies, your time, and obviously the application!

**Comment by thommcgrath** [comment]
This option will be available for Beacon 1.5.2 Beta 3. Barring any unforeseen problems, I expect this to be included in the stable 1.5.2 (and later) as well.
