### ISSUE TITLE
Getting multiple duplicate blueprints in the same drop

### ISSUE THREAD

**Issue by akmaslov** [thommcgrath/Beacon#76]
I have a setting for an item set that includes an entry for a set amount of ammunition (say, 20 tranq arrows) and a blueprint chance of 10%. Previously, I could only ever get one blueprint, but now I frequently get multiple. I remember we discussed this issue in #24 and you mentioned that, behind the scenes, you create a separate blueprint entry to avoid this case. 

From the resulting .ini string it seems we don't do that anymore. Was this an intentional change?

**Comment by thommcgrath** [comment]
It was intentional. The tactic had some side effects. For example, if you had 3 entries with a min and max of 3 selections, logically each of the 3 entries should always be selected. But since Beacon doubled the number of entries secretly, it was impossible to get the logic correct.

So Beacon now has a "Create Blueprint Entry" feature which is more similar to what Ark's default loot table does. Select a handful of items in an item set, right-click, and choose "Create Blueprint Entry" to group those items into a single entry with 100% blueprint chance while setting the others to 0%. You can then adjust the weight of that row to increase or decrease chances.

It's definitely not the same, but there's much less hidden behavior going on.

This change happened back in beta 8 and is documented in the release notes. https://beaconapp.cc/history.php#build8
